cmake_minimum_required(VERSION 3.10)
project(learnopengl)

set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

add_subdirectory(Window)
add_subdirectory(Triangle)
add_subdirectory(Square)
add_subdirectory(Shader)
add_subdirectory(Texture)
add_subdirectory(Transformation)
add_subdirectory(Coordinates)
add_subdirectory(Camera)
